baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'grlx.dev'
[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
      style = "catppuccin-latte"
[params.ui]
sidebar_menu_foldable = true
