baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'grlx.dev'
[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
      style = "catppuccin-latte"
[params.ui]
sidebar_menu_foldable = true
[[params.links.user]]
  name ="Twitter"
  url = "https://x.com/gogrlx"
  icon = "fab fa-twitter"
  desc = "Follow us on Twitter to get the latest news!"
[[params.links.user]]
  name = "GitHub"
  url = "https://github.com/gogrlx/grlx"
  icon = "fab fa-github"
  desc = "Development takes place here!"
